[tool.poetry]
name = "xx"
version = "0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
sceptre = "^4.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
